kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deeploy-node-tracker
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
