apiVersion: v1
kind: ConfigMap
metadata:
  name: core
  namespace: deeploy
data:
  # COMMON
  PORT: '3000'
  DB_SYNCHRONIZE: 'false'
  DB_LOGGING: 'false'
  DB_MIGRATIONS: 'true'
  KRATOS_ADMIN_URL: 'http://ory-kratos.deeploy.svc.cluster.local:8080/'
  AUTHORIZATION_URL: 'http://deeploy-core.deeploy.svc.cluster.local/'

  # DEPLOYMENT
  TOKEN_URL: 'http://deeploy-token.deeploy.svc.cluster.local/token/'
  SERVING_URL: 'http://deeploy-kfserving.deeploy.svc.cluster.local/deployments/'
  INTROSPECTOR_URL: 'http://deeploy-introspector.deeploy.svc.cluster.local/introspector/'
