apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-core
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-core
  template:
    metadata:
      labels:
        app: deeploy-core
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/core/configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/core/configSecret.yml") . | sha256sum }}
        checksum/database: {{ include (print $.Template.BasePath "/db/secret.yaml") . | sha256sum }}
        checksum/general-secret: {{ include (print $.Template.BasePath "/general_config/generalConfig.yaml") . | sha256sum }}
    spec:
      containers:
        - name: deeploy-core
          {{ if not .Values.devMode -}}
          image: "{{ .Values.images.registry }}{{ .Values.images.path }}/deeploy{{ template "awsExtension" . -}}:{{ .Values.images.tag }}"
          command:
            - "/bin/sh"
            - "./start.sh"
            - "core"
          {{- else -}}
          image: "deeploy-core"
          command:
            - "nest"
            - "start"
            - "core"
            - "--watch"
          {{- end }}
          env:
            {{ if .Values.devMode -}}
            - name: RUN_ENV
              value: 'tilt'
            {{- end }}
            {{ if not .Values.remoteBlobStorage.enabled -}}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: secretkey
            {{- else if and .Values.remoteBlobStorage.enabled (eq .Values.remoteBlobStorage.type "GCS") -}}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/usr/src/app/config/gcloud-application-credentials.json"
            {{- end }}
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: core
            - secretRef:
                name: general-config
            - secretRef:
                name: database
            - configMapRef:
                name: core
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      serviceAccountName: deeploy-deployment
      imagePullSecrets:
        - name: image-registry
      {{ if .Values.devMode -}}
      initContainers:
        - name: deeploy-core-init
          command:
            - '/bin/sh'
            - './start-dev.sh'
            - 'core'
          env:
            - name: RUN_ENV
              value: 'tilt'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          image: "deeploy-core"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: core
            - configMapRef:
                name: core
      {{- end }}
