kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deeploy-node-tracker
subjects:
  - kind: ServiceAccount
    name: deeploy-deployment
    namespace: deeploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deeploy-node-tracker
