apiVersion: v1
kind: Service
metadata:
  name: ory-kratos
  namespace: deeploy
spec:
  type: ClusterIP
  selector:
    app: ory-kratos
  ports:
    - port: 80
      name: public-ory-kratos
      targetPort: http-public
    - port: 8080
      name: admin-ory-kratos
      targetPort: http-admin
