apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  DB_NAME: deeploy
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: "5432"
  DB_USER: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}