apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  DB_NAME: deeploy
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: "5432"
  DB_USER: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}
  DB_SSL_ENABLED: {{ .Values.database.ssl.enabled | quote }}
  {{ if .Values.database.ssl.enabled -}}
  DB_CA: {{ .Values.database.ssl.ca | quote}}
  {{- end }}