apiVersion: v1
kind: Secret
metadata:
  name: authorization
  namespace: deeploy
type: Opaque
stringData:
  DB_TYPE: 'postgres'
  DB_NAME: deeploy_companies
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: '5432'
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
