apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-authorization
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-authorization
  template:
    metadata:
      labels:
        app: deeploy-authorization
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/authorization/configMap.yml") . | sha256sum }}
        checksum/general-secret: {{ include (print $.Template.BasePath "/general_config/generalConfig.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/authorization/configSecret.yml") . | sha256sum }}
    spec:
      containers:
        - name: deeploy-authorization
          {{ if not .Values.devMode -}}
          image: '{{ .Values.images.registry }}{{ .Values.images.path }}/deeploy:{{ .Values.images.tag }}'
          command:
            - '/bin/sh'
            - './start.sh'
            - 'authorization'
          {{- else -}}
          image: "deeploy-authorization"
          env:
            - name: RUN_ENV
              value: 'tilt'
          command:
            - "nest"
            - "start"
            - "authorization"
            - "--watch"
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: authorization
            - secretRef:
                name: general-config
            - configMapRef:
                name: authorization
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: image-registry
      {{ if .Values.devMode -}}
      initContainers:
        - name: deeploy-authorization-init
          command:
            - '/bin/sh'
            - './start-dev.sh'
            - 'authorization'
          env:
            - name: RUN_ENV
              value: 'tilt'
          image: "deeploy-authorization"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: authorization
            - configMapRef:
                name: authorization
      {{- end }}
