apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-authenticator
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-authenticator
  template:
    metadata:
      labels:
        app: deeploy-authenticator
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/authenticator/configMap.yml") . | sha256sum }}
        checksum/general-secret: {{ include (print $.Template.BasePath "/general_config/generalConfig.yaml") . | sha256sum }}
    spec:
      containers:
      - name: deeploy-authenticator
        {{ if not .Values.devMode -}}
        image: "{{ .Values.images.registry }}{{ .Values.images.path }}/authenticator:{{ .Values.images.tag }}"
        {{- else -}}
        image: "deeploy-authenticator"
        {{- end }}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        envFrom:
          - secretRef:
              name: general-config
          - configMapRef:
              name: authenticator
      imagePullSecrets:
        - name: image-registry
