apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-authenticator
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-authenticator
  template:
    metadata:
      labels:
        app: deeploy-authenticator
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/authenticator/configMap.yml") . | sha256sum }}
        checksum/general-secret: {{ include (print $.Template.BasePath "/general_config/generalConfig.yaml") . | sha256sum }}
    spec:
      containers:
      - name: deeploy-authenticator
        {{ if not .Values.devMode -}}
        image: "{{ .Values.images.registry }}{{ .Values.images.path }}/deeploy{{ template "awsExtension" . -}}:{{ .Values.images.tag }}"
        command:
            - "/bin/sh"
            - "./start.sh"
            - "authenticator"
        {{- else -}}
        image: "deeploy-authenticator"
          command:
            - "nest"
            - "start"
            - "authenticator"
            - "--watch"
          {{- end}}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        envFrom:
          - secretRef:
              name: general-config
          - configMapRef:
              name: authenticator
        readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: image-registry
