apiVersion: v1
kind: Service
metadata:
  name: deeploy-authenticator
  namespace: deeploy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      name: http-deeploy-authenticator
  selector:
    app: deeploy-authenticator
