apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: deeploy-authorization
  namespace: deeploy
spec:
  prefix: '/v2/(.*/authorization)'
  prefix_regex: true
  regex_rewrite:
    pattern: '/v2/(.*/authorization)'
    substitution: '/\1'
  service: deeploy-core.deeploy
  add_request_headers:
    x-is-public: 'true'
  timeout_ms: 60000
  cors:
    origins:
      - 'https://{{ .Values.host }}'
    methods:
      - POST
      - GET
      - OPTIONS
      - PUT
      - DELETE
      - HEAD
      - CONNECT
      - PATCH
    headers:
      - x-kratos-authenticated-identity-id
      - Authorization
      - Accept
      - Content-Type
    credentials: true
    