apiVersion: v1
kind: Service
metadata:
  name: deeploy-workspaces
  namespace: deeploy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http-deeploy-workspaces
  selector:
    app: deeploy-workspaces
