apiVersion: v1
kind: Secret
metadata:
  name: deployment
  namespace: deeploy
type: Opaque
stringData:
  DB_TYPE: "postgres"
  DB_NAME: deeploy_deployment
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: "5432"
  DB_USER: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}
