apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment
  namespace: deeploy
data:
  PORT: '3000'
  DB_SYNCHRONIZE: 'false'
  DB_LOGGING: 'false'
  DB_MIGRATIONS: 'true'
  DOMAIN: {{ .Values.host | quote }}
  TOKEN_URL: 'http://deeploy-token.deeploy.svc.cluster.local/token/'
  REPOSITORY_URL: 'http://deeploy-repository.deeploy.svc.cluster.local/'
  SERVING_URL: 'http://deeploy-kfserving.deeploy.svc.cluster.local/deployments/'
  INTROSPECTOR_URL: 'http://deeploy-introspector.deeploy.svc.cluster.local/introspector/'
  DEPLOYMENT_URL: 'http://deeploy-deployment.deeploy.svc.cluster.local/'
  KRATOS_ADMIN_URL: 'http://ory-kratos.deeploy.svc.cluster.local:8080/'
  WORKSPACES_URL: 'http://deeploy-workspaces.deeploy.svc.cluster.local/workspaces/'
  USER_URL: 'http://deeploy-user.deeploy.svc.cluster.local/'
