apiVersion: v1
kind: Secret
metadata:
  name: deployment
  namespace: deeploy
type: Opaque
stringData:
  {{ if not .Values.remoteBlobStorage.enabled -}}
  STORAGE_TYPE: "minio"
  MINIO_PORT: "9000"
  MINIO_DOMAIN: {{ template "minioDomain" . }}
  MINIO_SSL: "false"
  {{- else if and .Values.remoteBlobStorage.enabled (eq .Values.remoteBlobStorage.type "AWS_S3") -}}
  STORAGE_TYPE: "aws"
  S3_ACCESS_KEY: {{ .Values.remoteBlobStorage.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.remoteBlobStorage.s3SecretKey | quote }}
  BUCKET_NAME: {{ .Values.remoteBlobStorage.bucketName | quote }}
  {{- else if and .Values.remoteBlobStorage.enabled (eq .Values.remoteBlobStorage.type "GCS") -}}
  STORAGE_TYPE: "gcs"
  BUCKET_NAME: {{ .Values.remoteBlobStorage.bucketName | quote }}
  {{- end }}
