apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-deployment
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-deployment
  template:
    metadata:
      labels:
        app: deeploy-deployment
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/deployment/configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/deployment/configSecret.yml") . | sha256sum }}
    spec:
      containers:
        - name: deeploy-deployment
          {{ if not .Values.devMode -}}
          image: "{{ .Values.images.registry }}{{ .Values.images.path }}/deeploy:{{ .Values.images.tag }}"
          command:
            - "/bin/sh"
            - "./start.sh"
            - "deployment"
          {{- else -}}
          image: "deeploy-deployment"
          command:
            - "nest"
            - "start"
            - "deployment"
            - "--watch"
          {{- end }}
          env:
            {{ if .Values.devMode -}}
            - name: RUN_ENV
              value: 'tilt'
            {{- end }}
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: deployment
            - configMapRef:
                name: deployment
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: image-registry
      {{ if .Values.devMode -}}
      initContainers:
        - name: deeploy-deployment-init
          command:
            - '/bin/sh'
            - './start-dev.sh'
            - 'deployment'
          env:
            - name: RUN_ENV
              value: 'tilt'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          image: "deeploy-deployment"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: deployment
            - configMapRef:
                name: deployment
      {{- end }}
