apiVersion: v1
kind: Service
metadata:
  name: deeploy-logger
  namespace: deeploy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http-deeploy-logger
  selector:
    app: deeploy-logger
