apiVersion: v1
kind: ConfigMap
metadata:
  name: repository
  namespace: deeploy
data:
  PORT: '3000'
  DB_SYNCHRONIZE: 'false'
  DB_LOGGING: 'false'
  DB_MIGRATIONS: 'true'
  KRATOS_ADMIN_URL: 'http://ory-kratos.deeploy.svc.cluster.local:8080/'
  WORKSPACES_URL: 'http://deeploy-workspaces.deeploy.svc.cluster.local/workspaces/'
  DEPLOYMENT_URL: 'http://deeploy-deployment.deeploy.svc.cluster.local/'
