apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-repository
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-repository
  template:
    metadata:
      labels:
        app: deeploy-repository
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/repository/configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/repository/configSecret.yml") . | sha256sum }}
        checksum/general-secret: {{ include (print $.Template.BasePath "/general_config/generalConfig.yaml") . | sha256sum }}
        {{ if not .Values.remoteBlobStorage.enabled -}}
        checksum/s3: {{ include (print $.Template.BasePath "/kfserving/s3-secret.yml") . | sha256sum }}
        {{- end }}
    spec:
      containers:
        - name: deeploy-repository
          {{ if not .Values.devMode -}}
          image: "{{ .Values.images.registry }}{{ .Values.images.path }}/deeploy:{{ .Values.images.tag }}"
          command:
            - "/bin/sh"
            - "./start.sh"
            - "repository"
          {{- else -}}
          image: "deeploy-repository"
          command:
            - "nest"
            - "start"
            - "repository"
            - "--watch"
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DUMMY
              value: DUMMY
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            {{ if not .Values.remoteBlobStorage.enabled -}}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: secretkey
            {{- else if and .Values.remoteBlobStorage.enabled (eq .Values.remoteBlobStorage.type "GCS") -}}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/usr/src/app/config/gcloud-application-credentials.json"
            {{- end }}
            {{if .Values.devMode -}}
            - name: RUN_ENV
              value: 'tilt'
            {{- end }}
          envFrom:
            - secretRef:
                name: general-config
            - secretRef:
                name: repository
            - configMapRef:
                name: repository
          {{ if and .Values.remoteBlobStorage.enabled (eq .Values.remoteBlobStorage.type "GCS") -}}
          volumeMounts:
          - name: gcs-secret
            mountPath: "/usr/src/app/config/"
            readOnly: true
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      {{ if and .Values.remoteBlobStorage.enabled (eq .Values.remoteBlobStorage.type "GCS") -}}
      volumes:
      - name: gcs-secret
        secret:
          secretName: s3-secret
      {{- end }}
      imagePullSecrets:
        - name: image-registry
      {{ if .Values.devMode -}}
      initContainers:
        - name: deeploy-repository-init
          command:
            - '/bin/sh'
            - './start-dev.sh'
            - 'repository'
          env:
            - name: RUN_ENV
              value: 'tilt'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            {{ if not .Values.remoteBlobStorage.enabled -}}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: secretkey
            {{- else if and .Values.remoteBlobStorage.enabled (eq .Values.remoteBlobStorage.type "GCS") -}}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/usr/src/app/config/gcloud_application_credentials.json"
            {{- end }}
          image: "deeploy-repository"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: repository
            - configMapRef:
                name: repository
      {{- end }}
