apiVersion: v1
kind: Secret
metadata:
  name: token
  namespace: deeploy
type: Opaque
stringData:
  {{ if (eq .Values.security.keyManagement.kmsType "AWS") -}}
  KMS_TYPE: "aws"
  AWS_KMS_KEY_ID: {{ .Values.security.keyManagement.aws.keyId }}
  AWS_KMS_ACCESS_KEY: {{ .Values.security.keyManagement.aws.accessKey }}
  AWS_KMS_SECRET_KEY: {{ .Values.security.keyManagement.aws.secretKey }}
  {{- else if (eq .Values.security.keyManagement.kmsType "AZURE") -}}
  KMS_TYPE: "azure"
  AZURE_VAULT_KEY_ID: {{ .Values.security.keyManagement.azure.keyId }}
  AZURE_VAULT_NAME: {{ .Values.security.keyManagement.azure.vaultName }}
  AZURE_CLIENT_ID: {{ .Values.security.keyManagement.azure.clientId }}
  AZURE_CLIENT_SECRET: {{ .Values.security.keyManagement.azure.clientSecret }}
  AZURE_TENANT_ID: {{ .Values.security.keyManagement.azure.tenantId }}
  {{- end }}