apiVersion: v1
kind: ConfigMap
metadata:
  name: token
  namespace: deeploy
data:
  PORT: '3000'
  DB_SYNCHRONIZE: 'false'
  DB_LOGGING: 'false'
  DB_MIGRATIONS: 'true'
  DEPLOYMENT_URL: 'http://deeploy-core.deeploy.svc.cluster.local/'
  KRATOS_ADMIN_URL: 'http://ory-kratos.deeploy.svc.cluster.local:8080/'
