apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: deeploy
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
data:
  rabbitmq-username: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitmq-password: {{ randAlphaNum 30 | b64enc | quote }}
