apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: deeploy-user
  namespace: deeploy
spec:
  prefix: '/v2/(users($|/.*)|workspaces/([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})/users($|/.*))'
  prefix_regex: true
  regex_rewrite:
    pattern: '/v2/(users($|/.*)|workspaces/([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})/users($|/.*))'
    substitution: '/\1'
  service: deeploy-user.deeploy
  add_request_headers:
    x-is-public: 'true'
  cors:
    origins:
      - 'https://{{ .Values.host }}'
    methods:
      - POST
      - GET
      - OPTIONS
      - PUT
      - DELETE
      - HEAD
      - CONNECT
      - PATCH
    headers:
      - x-kratos-authenticated-identity-id
      - Authorization
      - Accept
      - Content-Type
    credentials: true
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: deeploy-user-swagger
  namespace: deeploy
spec:
  prefix: '/v2/users/swagger'
  rewrite: '/v2/users/swagger'
  service: deeploy-user.deeploy
  add_request_headers:
    x-is-public: 'true'
  cors:
    origins:
      - 'https://{{ .Values.host }}'
    methods:
      - POST
      - GET
      - OPTIONS
      - PUT
      - DELETE
      - HEAD
      - CONNECT
      - PATCH
    headers:
      - x-kratos-authenticated-identity-id
      - Authorization
      - Accept
      - Content-Type
    credentials: true
