apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: deeploy
type: Opaque
stringData:
  SMTP_URI: smtps://{{ .Values.email.username }}:{{ .Values.email.password }}@{{ .Values.email.smtpHost }}:{{ .Values.email.port }}?skip_ssl_verify=true
  ADMIN_EMAIL: {{ .Values.security.adminCredentials.email }}
  ADMIN_FIRST_NAME: {{ .Values.security.adminCredentials.firstName }}
  ADMIN_LAST_NAME: {{ .Values.security.adminCredentials.lastName }}
