apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    # TODO(mattmoor): We should not require any istio annotations.
    istio-injection: enabled
    serving.knative.dev/release: "v0.13.0"