apiVersion: v1
kind: Secret
metadata:
  name: notification
  namespace: deeploy
type: Opaque
stringData:
  SMTP_URI: smtps://{{ .Values.email.username }}:{{ .Values.email.password }}@{{ .Values.email.smtpHost }}:{{ .Values.email.port }}?skip_ssl_verify=true
