apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-notification
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-notification
  template:
    metadata:
      labels:
        app: deeploy-notification
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/notification/configMap.yml") . | sha256sum }}
        checksum/rabbitmq: {{ include (print $.Template.BasePath "/rabbitmq/secret.yaml") . | sha256sum }}
        checksum/database: {{ include (print $.Template.BasePath "/db/secret.yaml") . | sha256sum }}
        checksum/general-secret: {{ include (print $.Template.BasePath "/general_config/generalConfig.yaml") . | sha256sum }}
    spec:
      containers:
        - name: deeploy-notification
          {{ if not .Values.devMode -}}
          image: "{{ .Values.images.registry }}{{ .Values.images.path }}/deeploy{{ template "awsExtension" . -}}:{{ .Values.images.tag }}"
          command:
            - "/bin/sh"
            - "./start.sh"
            - "notification"
          {{- else -}}
          image: "deeploy-notification"
          command:
            - "nest"
            - "start"
            - "notification"
            - "--watch"
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            {{if .Values.devMode -}}
            - name: RUN_ENV
              value: 'tilt'
            {{- end }}
          envFrom:
            - secretRef:
                name: general-config
            - secretRef:
                name: database
            - configMapRef:
                name: notification
            - secretRef:
                name: notification
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: image-registry
      {{ if .Values.devMode -}}
      initContainers:
        - name: deeploy-notification-init
          command:
            - '/bin/sh'
            - './start-dev.sh'
            - 'notification'
          env:
            - name: RUN_ENV
              value: 'tilt'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          image: "deeploy-notification"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: notification
            - configMapRef:
                name: notification
      {{- end }}
