apiVersion: v1
kind: Secret
metadata:
    name: general-config
    namespace: deeploy
type: Opaque
stringData:
    DOMAIN: {{ .Values.host | quote }}
    LICENSE_TYPE: {{ .Values.license.type | quote }}
    {{ if not (eq .Values.license.type "AWS") -}}
    DEEPLOY_LICENSE_KEY: {{ .Values.license.deeployLicenseKey | quote }}
    {{- else -}}
    AWS_DEFAULT_REGION: {{ .Values.license.availabilityZone | quote }}
    {{- end }}