apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeploy-introspector
  namespace: deeploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deeploy-introspector
  template:
    metadata:
      labels:
        app: deeploy-introspector
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/introspector/configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/introspector/configSecret.yml") . | sha256sum }}
        checksum/rabbitmq: {{ include (print $.Template.BasePath "/rabbitmq/secret.yaml") . | sha256sum }}
        checksum/general-secret: {{ include (print $.Template.BasePath "/general_config/generalConfig.yaml") . | sha256sum }}
    spec:
      containers:
        - name: deeploy-introspector
          {{ if not .Values.devMode -}}
          image: "{{ .Values.images.registry }}{{ .Values.images.path }}/deeploy:{{ .Values.images.tag }}"
          command:
            - "/bin/sh"
            - "./start.sh"
            - "introspector"
          {{- else -}}
          image: "deeploy-introspector"
          command:
            - "nest"
            - "start"
            - "introspector"
            - "--watch"
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            {{if .Values.devMode -}}
            - name: RUN_ENV
              value: 'tilt'
            {{- end }}
          envFrom:
            - secretRef:
                name: introspector
            - secretRef:
                name: general-config
            - configMapRef:
                name: introspector
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: image-registry
      {{ if .Values.devMode -}}
      initContainers:
        - name: deeploy-introspector-init
          command:
            - '/bin/sh'
            - './start-dev.sh'
            - 'introspector'
          env:
            - name: RUN_ENV
              value: 'tilt'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          image: "deeploy-introspector"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: introspector
            - configMapRef:
                name: introspector
      {{- end }}
