# Default values for Deeploy.
devMode: false

images:
  registry: 709825985650.dkr.ecr.us-east-1.amazonaws.com
  path: /deeploy
  tag: '1.14.1'
  username:
  password:

host:

license:
  # 'AWS' or 'DEEPLOY'
  type: AWS
  availabilityZone: eu-central-1
  deeployLicenseKey:

email:
  username:
  password:
  smtpHost:
  port:
  fromAddress:

database:
  host:
  port:
  username:
  password:
  ssl:
    enabled: false
    ca:

remoteBlobStorage:
  enabled: true
  type: AWS_S3
  aws:
    bucketName:
    s3AccessKey:
    s3SecretKey:
  azure:
    subscriptionId:
    containerName:
    storageAccountName:
    tenantId:
    clientId:
    clientSecret:
  gcp:
    bucketName:
    gcloudApplicationCredentialsJson:

monitoring:
  enabled: false
  credentials:
    username:
    password:

security:
  tls:
    enabled: true

  keyManagement:
    kmsType: AWS
    aws:
      keyId:
      accessKey:
      secretKey:
    azure:
      keyId:
      vaultName:
      clientId:
      clientSecret:
      tenantId:

  adminCredentials:
    firstName:
    lastName:
    email:

ambassador:
  image:
    repository: docker.io/datawire/ambassador
    tag: 1.5.5
  enableAES: false
  service:
    type: ClusterIP
  replicaCount: 1

rabbitmq:
  auth:
    username: deeploy
    existingPasswordSecret: rabbitmq
  persistence:
    enabled: false

minio:
  enabled: false
  existingSecret: s3-secret
  persistence:
    size: 20Gi
  environment:
    MINIO_BROWSER: 'on'
    MINIO_API_READY_DEADLINE: '5s'
  resources:
    requests:
      memory: '256Mi'

dev:
  enabled: false
  runPreInstall: true
