apiVersion: v1
kind: Service
metadata:
  name: deeploy-manual
  namespace: deeploy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http-deeploy-manual
  selector:
    app: deeploy-manual