kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deeploy-usage-tracker
  namespace: deeploy
subjects:
  - kind: ServiceAccount
    name: deeploy-usage
    namespace: deeploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deeploy-usage-tracker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-namespaces-global
subjects:
  - kind: ServiceAccount
    name: deeploy-usage
    namespace: deeploy
roleRef:
  kind: ClusterRole
  name: namespace-tracker
  apiGroup: rbac.authorization.k8s.io
