apiVersion: v1
kind: Service
metadata:
  name: deeploy-usage
  namespace: deeploy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http-deeploy-usage
  selector:
    app: deeploy-usage
